require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::UsersController do
  before(:each) do
    login_user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::User. As you add validations to Admin::User, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString", "username" => "username" }
  end


  describe "GET index" do
    # login_user

    it "assigns all users as @users" do
      user = Admin::User.create! valid_attributes
      get :index, {}
      assigns(:users).should eq([subject.current_user, user])
    end
  end


  describe "GET new" do
    it "assigns a new user as @user" do
      get :new, {}
      assigns(:user).should be_a_new(Admin::User)
    end
  end

  describe "GET edit" do
    it "assigns the requested user as @user" do
      user = Admin::User.create! valid_attributes
      get :edit, {:id => user.to_param}
      assigns(:user).should eq(user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::User" do
        expect {
          post :create, {:admin_user => valid_attributes}
        }.to change(Admin::User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, {:admin_user => valid_attributes}
        assigns(:user).should be_a(Admin::User)
        assigns(:user).should be_persisted
      end

      it "redirects to the created user" do
        post :create, {:admin_user => valid_attributes}
        response.should redirect_to(admin_users_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::User.any_instance.stub(:valid?).and_return(false)
        post :create, {:admin_user => { "name" => "invalid value" }}
        assigns(:user).should be_a_new(Admin::User)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::User.any_instance.stub(:valid?).and_return(false)
        post :create, {:admin_user => { "name" => "invalid value" }}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user" do
        user = Admin::User.create! valid_attributes
        # Assuming there are no other users in the database, this
        # specifies that the Admin::User created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the requests.
        Admin::User.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => user.to_param, :admin_user => { "name" => "MyString" }}
      end

      it "assigns the requested user as @user" do
        user = Admin::User.create! valid_attributes
        put :update, {:id => user.to_param, :admin_user => valid_attributes}
        assigns(:user).should eq(user)
      end

      it "redirects to the user" do
        user = Admin::User.create! valid_attributes
        put :update, {:id => user.to_param, :admin_user  => valid_attributes}
        response.should redirect_to(admin_users_path)
      end
    end

    describe "with invalid params" do
      it "assigns the user as @user" do
        user = Admin::User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::User.any_instance.stub(:valid?).and_return(false)
        put :update, {:id => user.to_param, :admin_user  => { "name" => "invalid value" }}
        assigns(:user).should eq(user)
      end

      it "re-renders the 'edit' template" do
        user = Admin::User.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::User.any_instance.stub(:valid?).and_return(false)
        put :update, {:id => user.to_param, :admin_user  => { "name" => "invalid value" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user" do
      user = Admin::User.create! valid_attributes
      expect {
        delete :destroy, {:id => user.to_param}
      }.to change(Admin::User, :count).by(-1)
    end

    it "redirects to the users list" do
      user = Admin::User.create! valid_attributes
      delete :destroy, {:id => user.to_param}
      response.should redirect_to(admin_users_url)
    end
  end

end
