test:
  aleph_inbound_dir: 'spec/fixtures/aleph_data/inbound/'
  aleph_outbound_dir: 'spec/fixtures/aleph_data/outbound/'
  aleph_archive_dir: 'spec/fixtures/aleph_data/archive/'

development: &development
  aleph_inbound_dir: 'aleph_data/inbound/'
  aleph_outbound_dir: 'aleph_data/outbound/'
  aleph_archive_dir: 'aleph_data/archive/'

pre_production:
  aleph_inbound_dir: '/global/data/annex/pprd/inbound/'
  aleph_outbound_dir: '/global/data/annex/pprd/outbound/'
  aleph_archive_dir: '/global/data/annex/pprd/archive/'

prep:
  aleph_inbound_dir: '/api-gateway/annex/pprd/inbound/'
  aleph_outbound_dir: '/api-gateway/annex/pprd/outbound/'
  aleph_archive_dir: '/api-gateway/annex/pprd/archive/'


production:
  aleph_inbound_dir: '/api-gateway/annex/prod/inbound/'
  aleph_outbound_dir: '/api-gateway/annex/prod/outbound/'
  aleph_archive_dir: '/api-gateway/annex/prod/archive/'
